version: '3.8'

services:
  app:
    image: node:16
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    command: bash -c "yarn start"
