version: '3.8'

services:
  app:
    image: node:16
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    command: bash -c "yarn start"
